// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Test_project
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// All_game
        /// </summary>
        public void All_game()
        {
            #region Variable Declarations
            WinButton uINextButton = this.UIForm1Window.UINextWindow.UINextButton;
            WinButton uILoyalityButton = this.UIForm1Window.UILoyalityWindow.UILoyalityButton;
            WinButton uISendButton = this.UIForm1Window.UISendWindow.UISendButton;
            WinButton uIKnowledgeButton = this.UIForm1Window.UIKnowledgeWindow.UIKnowledgeButton;
            WinButton uINextButton1 = this.UIForm1Window.UINextWindow1.UINextButton;
            WinButton uIFinishButton = this.UIForm1Window.UIFinishWindow.UIFinishButton;
            WinButton uIInstallthevirusButton = this.UIForm1Window.UIInstallthevirusWindow.UIInstallthevirusButton;
            WinButton uIFinishButton1 = this.UIForm1Window.UIFinishWindow1.UIFinishButton;
            #endregion

            // Click 'Next ->' button
            Mouse.Click(uINextButton, new Point(50, 25));

            // Click 'Loyality' button
            Mouse.Click(uILoyalityButton, new Point(52, 4));

            // Click 'Send' button
            Mouse.Click(uISendButton, new Point(88, 12));

            // Click 'Knowledge' button
            Mouse.Click(uIKnowledgeButton, new Point(92, 16));

            // Double-Click 'Next ->' button
            Mouse.DoubleClick(uINextButton1, new Point(58, 16));

            // Double-Click 'Next ->' button
            Mouse.DoubleClick(uINextButton1, new Point(58, 16));

            // Click 'Next ->' button
            Mouse.Click(uINextButton1, new Point(58, 16));

            // Click 'Finish' button
            Mouse.Click(uIFinishButton, new Point(100, 16));

            // Click 'Install the virus' button
            Mouse.Click(uIInstallthevirusButton, new Point(41, 6));

            // Click 'Finish' button
            Mouse.Click(uIFinishButton1, new Point(107, 11));
        }
        
        #region Properties
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIForm1Window mUIForm1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UINextWindow UINextWindow
        {
            get
            {
                if ((this.mUINextWindow == null))
                {
                    this.mUINextWindow = new UINextWindow(this);
                }
                return this.mUINextWindow;
            }
        }
        
        public UILoyalityWindow UILoyalityWindow
        {
            get
            {
                if ((this.mUILoyalityWindow == null))
                {
                    this.mUILoyalityWindow = new UILoyalityWindow(this);
                }
                return this.mUILoyalityWindow;
            }
        }
        
        public UISendWindow UISendWindow
        {
            get
            {
                if ((this.mUISendWindow == null))
                {
                    this.mUISendWindow = new UISendWindow(this);
                }
                return this.mUISendWindow;
            }
        }
        
        public UIKnowledgeWindow UIKnowledgeWindow
        {
            get
            {
                if ((this.mUIKnowledgeWindow == null))
                {
                    this.mUIKnowledgeWindow = new UIKnowledgeWindow(this);
                }
                return this.mUIKnowledgeWindow;
            }
        }
        
        public UINextWindow1 UINextWindow1
        {
            get
            {
                if ((this.mUINextWindow1 == null))
                {
                    this.mUINextWindow1 = new UINextWindow1(this);
                }
                return this.mUINextWindow1;
            }
        }
        
        public UIFinishWindow UIFinishWindow
        {
            get
            {
                if ((this.mUIFinishWindow == null))
                {
                    this.mUIFinishWindow = new UIFinishWindow(this);
                }
                return this.mUIFinishWindow;
            }
        }
        
        public UIInstallthevirusWindow UIInstallthevirusWindow
        {
            get
            {
                if ((this.mUIInstallthevirusWindow == null))
                {
                    this.mUIInstallthevirusWindow = new UIInstallthevirusWindow(this);
                }
                return this.mUIInstallthevirusWindow;
            }
        }
        
        public UIFinishWindow1 UIFinishWindow1
        {
            get
            {
                if ((this.mUIFinishWindow1 == null))
                {
                    this.mUIFinishWindow1 = new UIFinishWindow1(this);
                }
                return this.mUIFinishWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UINextWindow mUINextWindow;
        
        private UILoyalityWindow mUILoyalityWindow;
        
        private UISendWindow mUISendWindow;
        
        private UIKnowledgeWindow mUIKnowledgeWindow;
        
        private UINextWindow1 mUINextWindow1;
        
        private UIFinishWindow mUIFinishWindow;
        
        private UIInstallthevirusWindow mUIInstallthevirusWindow;
        
        private UIFinishWindow1 mUIFinishWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UINextWindow : WinWindow
    {
        
        public UINextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UINextButton
        {
            get
            {
                if ((this.mUINextButton == null))
                {
                    this.mUINextButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINextButton.SearchProperties[WinButton.PropertyNames.Name] = "Next ->";
                    this.mUINextButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUINextButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINextButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UILoyalityWindow : WinWindow
    {
        
        public UILoyalityWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UILoyalityButton
        {
            get
            {
                if ((this.mUILoyalityButton == null))
                {
                    this.mUILoyalityButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILoyalityButton.SearchProperties[WinButton.PropertyNames.Name] = "Loyality";
                    this.mUILoyalityButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUILoyalityButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUILoyalityButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISendWindow : WinWindow
    {
        
        public UISendWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UISendButton
        {
            get
            {
                if ((this.mUISendButton == null))
                {
                    this.mUISendButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISendButton.SearchProperties[WinButton.PropertyNames.Name] = "Send";
                    this.mUISendButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUISendButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISendButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIKnowledgeWindow : WinWindow
    {
        
        public UIKnowledgeWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIKnowledgeButton
        {
            get
            {
                if ((this.mUIKnowledgeButton == null))
                {
                    this.mUIKnowledgeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIKnowledgeButton.SearchProperties[WinButton.PropertyNames.Name] = "Knowledge";
                    this.mUIKnowledgeButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIKnowledgeButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIKnowledgeButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UINextWindow1 : WinWindow
    {
        
        public UINextWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UINextButton
        {
            get
            {
                if ((this.mUINextButton == null))
                {
                    this.mUINextButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINextButton.SearchProperties[WinButton.PropertyNames.Name] = "Next ->";
                    this.mUINextButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUINextButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINextButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFinishWindow : WinWindow
    {
        
        public UIFinishWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIFinishButton
        {
            get
            {
                if ((this.mUIFinishButton == null))
                {
                    this.mUIFinishButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIFinishButton.SearchProperties[WinButton.PropertyNames.Name] = "Finish";
                    this.mUIFinishButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIFinishButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIFinishButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIInstallthevirusWindow : WinWindow
    {
        
        public UIInstallthevirusWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton3";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIInstallthevirusButton
        {
            get
            {
                if ((this.mUIInstallthevirusButton == null))
                {
                    this.mUIInstallthevirusButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIInstallthevirusButton.SearchProperties[WinButton.PropertyNames.Name] = "Install the virus";
                    this.mUIInstallthevirusButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIInstallthevirusButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIInstallthevirusButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFinishWindow1 : WinWindow
    {
        
        public UIFinishWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "specialButton1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIFinishButton
        {
            get
            {
                if ((this.mUIFinishButton == null))
                {
                    this.mUIFinishButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIFinishButton.SearchProperties[WinButton.PropertyNames.Name] = "Finish";
                    this.mUIFinishButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIFinishButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIFinishButton;
        #endregion
    }
}
